#!/bin/sh
echo \n\n
echo "******************* PRE COMMIT HOOK STARTED ***********************"
echo \n\n
npm ci
npm run test:recent
echo \n\n
echo "******************* PRE COMMIT HOOK FINISHED ***********************"
echo \n\n
