#!/bin/sh
printf "\n\n"
echo "******************* PRE COMMIT HOOK STARTED ***********************"
printf "\n\n"
npm ci
npm run test:recent
printf "\n\n"
echo "******************* PRE COMMIT HOOK FINISHED ***********************"
printf "\n\n"
