name: "Run On File Change"
description: "If given files changed, run the command"
inputs:
  files:
    description: Array of partial files, globs not supported yet
    required: true
    default: "[]"
  command:
    description: "Command to run if files were changed"
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - id: files
      name: Get changed files and compare
      uses: jitterbit/get-changed-files@v1
      run: |
        ./bin/files/changed.sh ${{ steps.files.outputs.all }} ${{ inputs.files }} ,
    # - name: "Check if files have changed, expectes values to be wrapped in quotes and comma seperated"
    #   run: ./bin/files/changed.sh ${{ inputs.files }} ,
    #   shell: bash
    - run: |
        if [ $? -eq 2 ];
        then
          echo Executing command "${{ inputs.command }}";
          eval ${{ inputs.command }}; 
        fi
      shell: bash