/**
 * Each array is ordered by what needs to be implemented first to last
 * The final one to implement is the key used to index this object
 */
const dependencies: { [i: string]: string[] } = {
    business: [],
    user: ["business"],
    event: ["business", "user"],
    permission: ["business", "user"],
    department: ["business", "user"],
    role: ["business", "user", "department", "permission"],
    userRole: ["business", "user", "department", "permission", "role"],
    manual: [
        "business",
        "user",
        "department",
        "permission",
        "role",
        "userRole",
    ],
    manualAssignment: [
        "business",
        "user",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
    ],
    manualSection: [
        "business",
        "user",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "manualAssignment",
    ],
    policy: [
        "business",
        "user",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "manualAssignment",
        "manualSection",
    ],
    content: [
        "business",
        "user",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "manualAssignment",
        "manualSection",
        "policy",
    ],
    policyRead: [
        "business",
        "user",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "manualAssignment",
        "manualSection",
        "policy",
    ],
    quiz: [
        "business",
        "user",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
    ],
    quizSection: [
        "business",
        "user",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "quiz",
    ],
    quizQuestion: [
        "business",
        "user",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "quiz",
        "quizSection",
    ],
    quizAnswer: [
        "business",
        "user",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "quiz",
        "quizSection",
        "quizQuestion",
    ],
    quizAttempt: [
        "business",
        "user",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "quiz",
    ],
    quizResult: [
        "business",
        "user",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "quiz",
        "quizSection",
        "quizQuestion",
        "quizAnswer",
        "quizAttempt",
    ],
};

export default dependencies;
