name: "Publish"
description: "publish debug files and test metadata"
runs:
  using: composite
  steps:
    - name: Publish test results
      uses: actions/upload-artifact@v2
      with:
        name: "test-report"
        path: |
          __test__/report.html
    - name: Publish code coverage 
      uses: actions/upload-artifact@v2
      with:
        name: "coverage"
        path: |
          coverage
          - uses: actions/upload-artifact@v2