name: "Publish"
description: "publish debug files and test metadata"
runs:
  using: composite
  steps:
    - name: Publish test results
      uses: actions/upload-artifact@v2
      with:
        name: "test-reports"
        path: |
          __test__/*-test-report.html