type ModelTest =
    | "business"
    | "membership"
    | "membershipRequest"
    | "user"
    | "permission"
    | "department"
    | "role"
    | "userRole"
    | "manual"
    | "manualAssignment"
    | "manualSection"
    | "policy"
    | "content"
    | "contentRead"
    | "quiz"
    | "quizSection"
    | "quizQuestionType"
    | "quizQuestion"
    | "quizAnswer"
    | "quizResult"
    | "quizAttempt"
    | "event";

export default ModelTest;
