name: "Continuous Integration"
description: "continuous integration"
inputs:
  changed:
    description: "either the commit hash or branch to compare against"
    required: true
    default: ""
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
    - name: install dependencies
      run: npm ci
      shell: bash
    - name: model tests
      run: |
        echo ${{ inputs.changed }}
        npm run test:jest -- --changedSince "${{ inputs.changed }}"
      shell: bash
    - name: api tests
      run: npm run test:cucumber
      shell: bash