name: "Continuous Integration"
description: "continuous integration"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
    - id: changed
      name: "Get changed"
      run: |
        if ${{ github.event_name }} == 'pull_request'; then
          # Gets the name out of the path
          BASE_REF_NAME="$(echo ${{ github.base_ref }} | rev | cut -d / -f 1 | rev)"
          VAL=origin/"$BASE_REF_NAME"
        else
          # Gets previous commit hash
          VAL=$(git rev-parse @~)
        fi
        echo "::set-output name=CHANGED::${VAL}"
      shell: bash
    - name: install dependencies
      run: npm ci
      shell: bash
    - name: model tests
      run: |
        npm run test:jest -- --changedSince "${{ steps.changed.outputs.CHANGED }}"
        npm run badges -- --ci
      shell: bash
    - name: api tests
      run: npm run test:cucumber
      shell: bash