import ModelTest from "@test/model";

/**
 * Each array is ordered by what needs to be implemented first to last
 * The final one to implement is the key used to index this object
 *
 * THE ONLY DIFFERENCE BETWEEN THIS AND THE MODEL TEARDOWN DEPENDENCIES IS ONE OF USER ROLE DEPENDENCIES
 * FRICKING STUPID
 */
const dependencies: { [i in ModelTest]: ModelTest[] } = {
    business: [],
    user: ["business"],
    membership: ["business", "user"],
    membershipRequest: ["business", "user"],
    event: ["business", "user", "membership"],
    permission: ["business", "user", "membership"],
    department: ["business", "user", "membership"],
    role: ["business", "user", "membership", "department", "permission"],
    userRole: [
        "business",
        "user",
        "membership",
        "membershipRequest",
        "department",
        "permission",
        "role",
        "event",
    ],
    manual: [
        "business",
        "user",
        "membership",
        "department",
        "permission",
        "role",
        "userRole",
    ],
    manualAssignment: [
        "business",
        "user",
        "membership",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
    ],
    manualSection: [
        "business",
        "user",
        "membership",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "manualAssignment",
    ],
    policy: [
        "business",
        "user",
        "membership",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "manualAssignment",
        "manualSection",
    ],
    content: [
        "business",
        "user",
        "membership",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "manualAssignment",
        "manualSection",
        "policy",
    ],
    policyRead: [
        "business",
        "user",
        "membership",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "manualAssignment",
        "manualSection",
        "policy",
    ],
    quiz: [
        "business",
        "user",
        "membership",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
    ],
    quizSection: [
        "business",
        "user",
        "membership",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "quiz",
    ],
    quizQuestion: [
        "business",
        "user",
        "membership",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "quiz",
        "quizSection",
    ],
    quizAnswer: [
        "business",
        "user",
        "membership",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "quiz",
        "quizSection",
        "quizQuestion",
    ],
    quizAttempt: [
        "business",
        "user",
        "membership",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "quiz",
    ],
    quizResult: [
        "business",
        "user",
        "membership",
        "department",
        "permission",
        "role",
        "userRole",
        "manual",
        "quiz",
        "quizSection",
        "quizQuestion",
        "quizAnswer",
        "quizAttempt",
    ],
};

export default dependencies;
