name: Continuous Integration 

on:
  push:
    branches:
        - "*"
        - "!main"
  pull_request:
    branches: 
     - '*'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install dependencies
        run: npm i
      - name: unit test
        run: npm run unit-test
      - name: bdd test
        run: npm run bdd-test