name: Checks
on:
  push:
    branches:
      - "*"
      - "!main"
  pull_request:
    branches:
      - "*"

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: cache node modules
        uses: ./.github/actions/cache-node-modules
      - name: check formatting
        run: npm run format:check
  check-api-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Check API Documentation"
        uses: ./.github/actions/check-documentation
        with:
          doc: ./README.md
          routes: ./src/routes/ 
  continuous-integration:
    env:
      DB: ${{ secrets.DB }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_PWD: ${{ secrets.DB_PWD }}
      DB_TYPE: ${{ secrets.DB_TYPE }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      ENABLE_MULTITHREADING: ${{ secrets.ENABLE_MULTITHREADING }}
      ENV_DEV_CLIENT: ${{ secrets.ENV_DEV_CLIENT }}
      ENV_LOCAL_CLIENT: ${{ secrets.ENV_LOCAL_CLIENT }}
      ENV_PROD_CLIENT: ${{ secrets.ENV_PROD_CLIENT }}
      ENV_LOCAL_SERVER: ${{ secrets.ENV_LOCAL_SERVER }}
      ENV_DEV_SERVER: ${{ secrets.ENV_DEV_SERVER }}
      ENV_PROD_SERVER: ${{ secrets.ENV_PROD_SERVER }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      MAIL_PWD: ${{ secrets.MAIL_PWD }}
      MAIL_USER: ${{ secrets.MAIL_USER }}
      PORT: ${{ secrets.PORT }}
      SESSION_ID: ${{ secrets.SESSION_ID }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      TARGET_ENV: ${{ secrets.TARGET_ENV }}
      SECONDARY_TEST_EMAIL: ${{ secrets.SECONDARY_TEST_EMAIL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: ci
        uses: ./.github/actions/ci
        continue-on-error: true
      - name: Publish npm log
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: "npm-log"
          path: "/home/runner/.npm/_logs"
      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: "test-results-and-coverage"
          path: |
            __test__/test-report.html
            __test__/coverage
